Vagrant::Config.run do |config|
  config.vm.guest = :solaris
  config.vm.box = 'solaris11'
  config.vm.box_url = 'https://s3.amazonaws.com/vboxes-2112/solaris11.box'
  config.vm.customize ["modifyvm", :id, "--memory", 2048]
  config.vm.network :hostonly, '10.11.12.13'
  #config.vm.share_folder 'vagrant-root', '/vagrant', '.', :nfs => true
end
